### ISSUE TITLE
Add ChEBI column to all imported pathways

### ISSUE THREAD

**Issue by AlexanderPico** [wikipathways/cytoscape-wikipathways-app#110]
Analogous to the Ensembl column that you add, it would be great to have a "ChEBI" column that attempts to map from all ID types for metabolites to ChEBI.  

You might also look into adding a a "SMILE" column with SMILE strings that you can also get from the BridgeDb web service. This would allow ChemViz app to generate metabolite structures to view on the nodes.

**Comment by AlexanderPico** [comment]
Asking Scooter for preference among SMILE, InChI and InChI Key...

**Comment by DeniseSl22** [comment]
Just some point to think about for this addition:
1. We're now unifying chebi IDs to not contain the "CHEBI:" prefix before the ID (in the WP RDF, and a bot that @mkutmon wrote also unified the GPMLs in this aspect). This is also in line with ChEBI ID modeling in Wikidata. These changes were made a few weeks/months ago, since @Anders was running into issues converting IDs for scholia pages (if I'm correct). So, the column now saying "xrefID" in the app could also consider using the same unification (so we're showing our data in the same manner).
1. We've also recently unified all the HMDB IDs; "old" structure was: HMDB00078, new is HMDB0000078 (so two additional 00 between 'HMDB' and ID number). I think the app is displaying this correctly, but would be good to check.
1. Regarding adding an additional column, BridgeDb support ChEBI, InChI, InChI-Key, SMILES (canonical and isomeric) (and many more of course). I've checked the ChemViz app from @scooter, didn't work with InChI-Key (yet), but with inchi. If that app could also work with InChI-Key, that would (I believe) be beneficial. The InChI-key has a set length  (see image below), which SMILES and InChI do not have:
![image](https://user-images.githubusercontent.com/26277832/72972053-0208ad80-3dcb-11ea-98f8-a307a42f3c45.png)
It could be that for large molecules, the SMILES and InChI become so long, that they are over 400 characters. And, if the InChI-Key is used, the ChEBI column would not be needed (since people can use the InChI-Key directly for mapping and also for chemviz).
Again, it's all supported in BridgeDb (although in the WP RDF we now have the InChI-key included, not SMILES and InChI, due to the unpredictable length of the 2 latter ones).

@egonw might also have some additional ideas, but the above is a summary of my point of view ;)
