### ISSUE TITLE
Features to keep in unreleased work

### ISSUE THREAD

**Issue by ariutta** [wikipathways/cytoscape-wikipathways-app#117]
There are one or two pre-release features that Adam worked on that we want to make sure to retain:
1. make it possible to edit columns in the Network Table
   - Maybe pre-release version 3.3.7-7: [jar](https://github.com/wikipathways/cytoscape-wikipathways-app/blob/develop/WikiPathways-3.3.77.jar) and a [commit](https://github.com/wikipathways/cytoscape-wikipathways-app/commit/911af3880cd0b436da24bd1c0c8dd461f05f8887) approximately corresponding to that timeframe
2. make it possible to open GPML from file
    - not sure, but maybe this was pre-release version 3.3.7-2? [Here's the jar](https://www.dropbox.com/s/twjhma9blo5582m/WikiPathways-v3.3.7-2.jar?dl=0) for 3.3.7-2.

**Comment by AlexanderPico** [comment]
I just made an official 3.3.8 release (https://apps.cytoscape.org/apps/wikipathways) in order to fix the log4shell vulnerability and these features are present.

This was a build from the `develop` branch, which appeared to be more up-to-date than `main`.

So, I think this issue is closed, but there may be other features/bugs lost from the `main` branch. Need to check...
