### ISSUE TITLE
Error when opening pathway

### ISSUE THREAD

**Issue by khanspers** [wikipathways/cytoscape-wikipathways-app#56]
Got this error with two different pathways (Human Statin and Human Apoptosis), when importing either as network or pathway. The pathway still loads and a view is create.

Maybe related to https://github.com/wikipathways/cytoscape-wikipathways-app/issues/49
![screen shot 2017-10-18 at 2 02 45 pm](https://user-images.githubusercontent.com/1442197/31746344-c7f9c47a-b41b-11e7-8d5c-aaba5619ed1a.png)

**Comment by AlexanderPico** [comment]
Ok. Tracked this one down... sort of.

I tested multiple versions of the app over the past 6 months and they all now trigger this error (when they definitely didn't before).  So, then I started testing older builds of Cytoscape. I have a 3.6.0 from Sept 22nd and it does NOT have this error!

The error is definitely in Cytoscape core code and it was due to a change between 9/22 and 10/18.

**Comment by AlexanderPico** [comment]
Ok. I think I found it...

https://github.com/cytoscape/cytoscape-impl/blob/develop/core-task-impl/src/main/java/org/cytoscape/task/internal/view/CreateNetworkViewTask.java#L219

This was checked in last week. Adam, do you want to try modifying this and retesting?

**Comment by AdamStuart** [comment]
resolved with Alex's fix
